# Generated by Django 2.2.2 on 2019-10-11 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('phone_no', models.CharField(max_length=15)),
                ('preffered_delivery_addr', models.TextField()),
                ('alt_addr_1', models.TextField(blank=True, null=True)),
                ('alt_addr_2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('order_time', models.TimeField(auto_now=True)),
                ('paid_for', models.BooleanField()),
                ('delivery_addr', models.TextField()),
                ('delivery_date', models.DateField()),
                ('buyer_firstname', models.CharField(max_length=200)),
                ('buyer_lastname', models.CharField(max_length=200)),
                ('buyer_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('buyer_phone_no', models.CharField(max_length=15)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='MarketWomanPH', max_length=200)),
                ('phone_number', models.CharField(max_length=16)),
                ('phone_number_2', models.CharField(default=None, max_length=16, null=True)),
                ('address', models.TextField(default='Coca-cola junction, Trans-Amadi way')),
                ('email', models.EmailField(default='hero4barca@gmail.com', max_length=254)),
                ('site_domain', models.CharField(default='www.marketwoman.com.ng', max_length=200)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'customer'), ('staff', 'staff')], max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GorceryDelivery.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GorceryDelivery.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('payment_type', models.CharField(max_length=200)),
                ('token_identifier', models.CharField(max_length=200)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_item_desc', models.TextField(null=True)),
                ('order_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_by_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Item')),
                ('measure', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.SalesMeasure')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GorceryDelivery.Order')),
                ('presentation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Presentation')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.UserProfile'),
        ),
    ]
