# Generated by Django 2.2.2 on 2019-07-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GorceryDelivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
