# Generated by Django 2.2.2 on 2019-07-05 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GorceryDelivery', '0002_category_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('phone_no', models.CharField(max_length=15)),
                ('preffered_delivery_addr', models.TextField()),
                ('alt_addr_1', models.TextField()),
                ('alt_addr_2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='item_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('order_time', models.TimeField(auto_now=True)),
                ('paid_for', models.BooleanField()),
                ('delivery_addr', models.TextField()),
                ('delivery_date', models.DateField()),
                ('buyer_firstname', models.CharField(max_length=200)),
                ('buyer_lastname', models.CharField(max_length=200)),
                ('buyer_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('buyer_phone_no', models.CharField(max_length=15)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='availability',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'customer'), ('staff', 'staff')], max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('payment_type', models.CharField(max_length=200)),
                ('token_identifier', models.CharField(max_length=200)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GorceryDelivery.Order')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.UserProfile'),
        ),
    ]
