# Generated by Django 2.2.2 on 2019-07-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GorceryDelivery', '0004_measure_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Category'),
        ),
    ]
