# Generated by Django 2.2.2 on 2019-08-02 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GorceryDelivery', '0009_ccategory_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='multiple_measure',
        ),
        migrations.RemoveField(
            model_name='salesmeasure',
            name='default_measure',
        ),
        migrations.AddField(
            model_name='presentation',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesmeasure',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='alt_addr_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='alt_addr_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
