# Generated by Django 2.2.2 on 2019-10-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GorceryDelivery', '0014_auto_20190926_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Category'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='presentation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Presentation'),
        ),
    ]
