# Generated by Django 2.2.2 on 2019-10-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GorceryDelivery', '0016_shop_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Category'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='presentation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GorceryDelivery.Presentation'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
